// File generated from our OpenAPI spec by Stainless.

package com.phoebe.api.models.product.lists.historical

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.phoebe.api.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class HistoricalRetrieveResponseTest {

    @Test
    fun create() {
        val historicalRetrieveResponse =
            HistoricalRetrieveResponse.builder()
                .allObsReported(true)
                .checklistId("checklistId")
                .creationDt("creationDt")
                .durationHrs(0.0)
                .isoObsDate("isoObsDate")
                .lastEditedDt("lastEditedDt")
                .loc(
                    HistoricalRetrieveResponse.Loc.builder()
                        .countryCode("countryCode")
                        .countryName("countryName")
                        .hierarchicalName("hierarchicalName")
                        .isHotspot(true)
                        .lat(0.0)
                        .latitude(0.0)
                        .lng(0.0)
                        .locId("locId")
                        .locName("locName")
                        .longitude(0.0)
                        .name("name")
                        .subnational1Code("subnational1Code")
                        .subnational1Name("subnational1Name")
                        .build()
                )
                .locId("locId")
                .numObservers(0L)
                .numSpecies(0)
                .addOb(
                    HistoricalRetrieveResponse.Ob.builder()
                        .addObsAux(
                            HistoricalRetrieveResponse.Ob.ObsAux.builder()
                                .auxCode("auxCode")
                                .entryMethodCode("entryMethodCode")
                                .fieldName("fieldName")
                                .obsId("obsId")
                                .speciesCode("speciesCode")
                                .subId("subId")
                                .value("value")
                                .build()
                        )
                        .obsDt("obsDt")
                        .obsId("obsId")
                        .speciesCode("speciesCode")
                        .build()
                )
                .obsDt("obsDt")
                .obsTime("obsTime")
                .obsTimeValid(true)
                .projId("projId")
                .protocolId("protocolId")
                .subId("subId")
                .submissionMethodCode("submissionMethodCode")
                .subnational1Code("subnational1Code")
                .userDisplayName("userDisplayName")
                .build()

        assertThat(historicalRetrieveResponse.allObsReported()).isEqualTo(true)
        assertThat(historicalRetrieveResponse.checklistId()).isEqualTo("checklistId")
        assertThat(historicalRetrieveResponse.creationDt()).isEqualTo("creationDt")
        assertThat(historicalRetrieveResponse.durationHrs()).isEqualTo(0.0)
        assertThat(historicalRetrieveResponse.isoObsDate()).isEqualTo("isoObsDate")
        assertThat(historicalRetrieveResponse.lastEditedDt()).isEqualTo("lastEditedDt")
        assertThat(historicalRetrieveResponse.loc())
            .isEqualTo(
                HistoricalRetrieveResponse.Loc.builder()
                    .countryCode("countryCode")
                    .countryName("countryName")
                    .hierarchicalName("hierarchicalName")
                    .isHotspot(true)
                    .lat(0.0)
                    .latitude(0.0)
                    .lng(0.0)
                    .locId("locId")
                    .locName("locName")
                    .longitude(0.0)
                    .name("name")
                    .subnational1Code("subnational1Code")
                    .subnational1Name("subnational1Name")
                    .build()
            )
        assertThat(historicalRetrieveResponse.locId()).isEqualTo("locId")
        assertThat(historicalRetrieveResponse.numObservers()).isEqualTo(0L)
        assertThat(historicalRetrieveResponse.numSpecies()).isEqualTo(0)
        assertThat(historicalRetrieveResponse.obs())
            .containsExactly(
                HistoricalRetrieveResponse.Ob.builder()
                    .addObsAux(
                        HistoricalRetrieveResponse.Ob.ObsAux.builder()
                            .auxCode("auxCode")
                            .entryMethodCode("entryMethodCode")
                            .fieldName("fieldName")
                            .obsId("obsId")
                            .speciesCode("speciesCode")
                            .subId("subId")
                            .value("value")
                            .build()
                    )
                    .obsDt("obsDt")
                    .obsId("obsId")
                    .speciesCode("speciesCode")
                    .build()
            )
        assertThat(historicalRetrieveResponse.obsDt()).isEqualTo("obsDt")
        assertThat(historicalRetrieveResponse.obsTime()).isEqualTo("obsTime")
        assertThat(historicalRetrieveResponse.obsTimeValid()).isEqualTo(true)
        assertThat(historicalRetrieveResponse.projId()).isEqualTo("projId")
        assertThat(historicalRetrieveResponse.protocolId()).isEqualTo("protocolId")
        assertThat(historicalRetrieveResponse.subId()).isEqualTo("subId")
        assertThat(historicalRetrieveResponse.submissionMethodCode())
            .isEqualTo("submissionMethodCode")
        assertThat(historicalRetrieveResponse.subnational1Code()).isEqualTo("subnational1Code")
        assertThat(historicalRetrieveResponse.userDisplayName()).isEqualTo("userDisplayName")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val historicalRetrieveResponse =
            HistoricalRetrieveResponse.builder()
                .allObsReported(true)
                .checklistId("checklistId")
                .creationDt("creationDt")
                .durationHrs(0.0)
                .isoObsDate("isoObsDate")
                .lastEditedDt("lastEditedDt")
                .loc(
                    HistoricalRetrieveResponse.Loc.builder()
                        .countryCode("countryCode")
                        .countryName("countryName")
                        .hierarchicalName("hierarchicalName")
                        .isHotspot(true)
                        .lat(0.0)
                        .latitude(0.0)
                        .lng(0.0)
                        .locId("locId")
                        .locName("locName")
                        .longitude(0.0)
                        .name("name")
                        .subnational1Code("subnational1Code")
                        .subnational1Name("subnational1Name")
                        .build()
                )
                .locId("locId")
                .numObservers(0L)
                .numSpecies(0)
                .addOb(
                    HistoricalRetrieveResponse.Ob.builder()
                        .addObsAux(
                            HistoricalRetrieveResponse.Ob.ObsAux.builder()
                                .auxCode("auxCode")
                                .entryMethodCode("entryMethodCode")
                                .fieldName("fieldName")
                                .obsId("obsId")
                                .speciesCode("speciesCode")
                                .subId("subId")
                                .value("value")
                                .build()
                        )
                        .obsDt("obsDt")
                        .obsId("obsId")
                        .speciesCode("speciesCode")
                        .build()
                )
                .obsDt("obsDt")
                .obsTime("obsTime")
                .obsTimeValid(true)
                .projId("projId")
                .protocolId("protocolId")
                .subId("subId")
                .submissionMethodCode("submissionMethodCode")
                .subnational1Code("subnational1Code")
                .userDisplayName("userDisplayName")
                .build()

        val roundtrippedHistoricalRetrieveResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(historicalRetrieveResponse),
                jacksonTypeRef<HistoricalRetrieveResponse>(),
            )

        assertThat(roundtrippedHistoricalRetrieveResponse).isEqualTo(historicalRetrieveResponse)
    }
}
